import pymysql
conn = pymysql.connect(host='localhost', user='root', password='123456', db='termshop', charset='utf8mb4')
cur = conn.cursor()
cur.execute('UPDATE orders SET merchant_id=2 WHERE merchant_id IS NULL LIMIT 5')
print('update null merchant_id rows:', cur.rowcount)
cur.execute('UPDATE orders SET merchant_id=2 WHERE merchant_id=638')
print('update 638 -> 2 rows:', cur.rowcount)
cur.execute('SELECT id, order_no, merchant_id, user_id, status FROM orders ORDER BY id DESC LIMIT 10')
for r in cur.fetchall(): print(r)
cur.execute("SHOW TABLES LIKE '%user%'")
print('user tables:', [r[0] for r in cur.fetchall()])
cur.execute("SHOW TABLES LIKE '%address%'")
print('address tables:', [r[0] for r in cur.fetchall()])
conn.commit()
conn.close()
